require("dotenv").config();

const {
  REACT_APP_ALGOLIA_APP_ID,
  REACT_APP_ALGOLIA_API_KEY,
  REACT_APP_ALGOLIA_INDEX_NAME,
  REACT_APP_GOOGLE_URL,
  REACT_APP_GETTOKEN_API,
  REACT_APP_UPDATE_DATA_API,
  REACT_APP_CONFLUENCE_UPDATE_API,
  REACT_APP_UPDATE_GOOGLE_DATA_API,
  REACT_APP_GOOGLE_CLIENT_ID,
  REACT_APP_GOOLGE_DRIVE_SCOPE,
  REACT_APP_CONFLUENCE_AUTH_API,
  REACT_APP_JIRA_AUTH,
} = process.env;

const config = {
  algoliaId: REACT_APP_ALGOLIA_APP_ID,
  algoliaApiKey: REACT_APP_ALGOLIA_API_KEY,
  algoliaIndexName: REACT_APP_ALGOLIA_INDEX_NAME,
  googleUrl: REACT_APP_GOOGLE_URL,
  getTokenApi: REACT_APP_GETTOKEN_API,
  updateDataApi: REACT_APP_UPDATE_DATA_API,
  confluenceUpdateApi: REACT_APP_CONFLUENCE_UPDATE_API,
  confluenceAuthApi: REACT_APP_CONFLUENCE_AUTH_API,
  updateGoogleDataApi: REACT_APP_UPDATE_GOOGLE_DATA_API,
  googleClientId: REACT_APP_GOOGLE_CLIENT_ID,
  googleDriveScope: REACT_APP_GOOLGE_DRIVE_SCOPE,
  jiraAuth: REACT_APP_JIRA_AUTH,
};

export default config;
